version: 2.1
orbs:
    coralogix: coralogix/coralogix@0.3.0
jobs:
  build:
    docker:
      - image: cimg/go:1.13
    steps:
      - checkout
      - run: go build -o main
  test:
    docker:
      - image: cimg/go:1.13
    steps:
      - checkout
      - run: go test -v
workflows:
  build_and_test:
    jobs:
      - build 
      - test:
          requires:
            - build
      - coralogix/stats:
          keep_artifacts: true
      - coralogix/logs:
          keep_artifacts: true
