version: 2.1
jobs:
  build:
    docker:
      - image: cimg/go:1.13
    steps:
      - checkout
      - run: go build -o main
  test:
    docker:
      - image: cimg/go:1.13
    steps:
      - checkout
      - run: go test
workflows:
  build_and_test:
    jobs:
      - build
      - test
